[project]
name = "neutron-bsdbridge"
version = "0.0.0"
description = "Neutron ML2 driver with L2, DHCP and L3 agents based on if_bridge and pf for FreeBSD"
readme = "README.md"
authors = [
    { name = "joshiggins", email = "josh@joshh.info" }
]
license = {text = "Apache-2.0"}
requires-python = ">=3.12"
dependencies = []

[project.entry-points."neutron.ml2.mechanism_drivers"]
bsdbridge = "neutron_bsdbridge.mech:BsdBridgeMechanismDriver"

[project.scripts]
neutron-bsdbridge-l2-agent = "neutron_bsdbridge.l2_agent.agent:main"
neutron-bsdbridge-dhcp-agent = "neutron_bsdbridge.dhcp_agent.agent:main"
neutron-bsdbridge-l3-agent = "neutron_bsdbridge.l3_agent.agent:main"

[build-system]
requires = ["uv_build>=0.11.28"]
build-backend = "uv_build"
